version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-sass
    versions:
    - 4.0.2
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.0.1
    - 3.1.0
    - 3.1.1
  - dependency-name: gatsby
    versions:
    - 3.0.4
    - 3.1.0
    - 3.1.1
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react-images
    versions:
    - 1.0.0
